version: "3.9"
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fyyur
      - POSTGRES_USER=fyyur
      - POSTGRES_PASSWORD=fyyur
    container_name: fyyur_db
  fyyur:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlosvalarezo/fyyur
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - PORT=5000
      - DB_NAME=fyyur
      - DB_USER=fyyur
      - DB_PASSWORD=fyyur
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
    restart: on-failure:10
    volumes:
      - .:/fyyur
    container_name: fyyur